---
- hosts: all
  tasks:
    - name: Install HTTPD 
      yum:
        name: "{{ item }}"
        state: latest 
      with_items:
        - httpd
        - curl
      become: true

    - name: Start HTTPD
      service: 
        name: httpd
        state: started
      become: true 
