---
- hosts: all
  tasks:
    - name: Install HTTPD 
      yum:
        name: httpd
        state: latest 
      become: true

    - name: Start HTTPD
      service: 
        name: httpd
        state: started
      become: true 
